what-is-your-ideal-type/FE_what-is-your-ideal-type

src/App.tsx

test: git test

---

package-lock.json
package.json
postcss.config.js
src/App.tsx
src/Pages/SignUp.tsx
src/index.css
src/index.tsx
tailwind.config.js

> Tailwind를 추가했습니다. className으로 스타일링 하시면 됩니다
> SignUp page 마크업과 스타일링 간단하게 하였습니다.
> App.tsx에 import구문에 버그가 있길래 수정했습니다

tailwind css 추가, SignUp page 스타일링, import 버그 수정

---

src/index.css
tailwind.config.js

color 사용하실 때는
className에 "text-main" 이런식으로 넣으시면 됩니다.

Feat: 공통 CSS 설정

---

src/App.tsx
src/Pages/Main.tsx
src/Pages/Survey.tsx

> Survey 페이지에서 이전/다음 버튼 없이 응답을 선택하면 바로 다음 페이지로 넘어갈 수 있도록 수정했습니다.
마지막 질문에서는 응답을 제출하겠냐는 alert과 함께 확인을 누르면 응답이 출력되도록 함수를 수정했습니다.
> 라우터 "/" 를 Home 컴포넌트로 변경하고 기존 Main 컴포넌트는 삭제하였습니다.

Fix: Survey 버튼 수정, ui 수정

---

labels.json
package-lock.json
package.json
src/App.tsx
src/services/imageGenerator.tsx

> #23 
> Open AI를 활용해 Prompt로 요청을 보내고 그에 상응하는 이미지를 응답받는 로직을 작성했습니다.
> Label  적용 해보겠습니다
> API 요청 남발을 방지하기 위해 key를 잠시 비활성화 했습니다. 테스트는 mock 이미지로 할 예정입니다!

Feat: Open AI API 로직 구현

---

package-lock.json
package.json
src/App.tsx
src/Pages/Home.tsx
src/Pages/SignUp.tsx
src/firebase.ts

> firebase 연동했고, 회원가입 validation 넣었습니다.
회원가입 시 입력한 이메일, 비밀번호는 firestore db에 저장할 수 있게 했습니다.
이메일, 비밀번호 확인 후 로그인할 수 있게 추가했습니다.

Feat: firebase 연동 및 회원가입 validation 추가

---

src/App.tsx

> App.tsx에서 firebase api key로 인한 오류나는 부분 일단 주석처리함

Fix: firebase api key로 인한 오류나는 부분 일단 주석처리함

---

src/Pages/SignUp.tsx

> 회원가입 비밀번호 재확인 input 입력시 input값 지워지는 버그 수정했습니다.

Fix: 회원가입 input 입력값 버그 수정

---

package-lock.json
package.json
src/Pages/Home.tsx
src/contexts/AuthContext.tsx
src/services/uploadImage.ts

> #63 Refator: 로그인 인증 세션 지속성
> 1. UUID 사용해 이미지 파일명이 랜덤을 저장되게 했습니다.
2. 로그아웃을 하지 않았을 경우를 대비해, setPersistence 함수를 사용하여 Firebase 인증 지속성을 browserSessionPersistence로 설정했습니다. 브라우저 탭을 닫으면 인증 세션이 종료됩니다.
3. 로그인/로그아웃에 따른 Home 페이지 구현 수정했습니다. 로그아웃하여 인증 세션 종료하는 것도 추가했습니다.
> UUID 를 추가했으니 `npm i` 하시면 됩니다.
> 로그인 한 경우, Home 페이지에 로고, 마이페이지와 로그아웃 버튼이 나오게 한 상태입니다. 더 개선하면 좋을 것 같긴 합니다. 아이디어가 있다면 나눠보고 반영해도 좋을 것 같습니다.

Feat: 이미지 파일명 랜덤 생성, 로그아웃 기능 추가, Refactor: 브라우저 탭 닫으면 인증 지속 종료

---

src/Pages/Generate.tsx
src/Pages/Survey.tsx
src/components/Survey.ts
src/services/imageGenerator.ts

> #56 
> 영어로 프롬프트를 변경했습니다.
> 작업을 위해 사용자에게는 한글(label)로 리스트업하고 데이터는 영어(value)로 처리하게끔 했습니다.
> 요청을 상태를 배열로 받은뒤에 보내기 때문에 input radio로 할 필요가 없고 가독성이 좋지않아 리팩토링 진행했습니다. 
> 버튼 컴포넌트로 리스트업해서 스타일이 완성되지는 못했습니다. 스타일 수정이 필요한데 1차 테스트 전까지 진행해보겠습니다.
> 작성한 프롬프트 그대로 요청 가는 것을 확인
> 테스트를 진행해보시고 이상이 있으시다면 꼭 말씀 주세요!
> Button 컴포넌트에 스타일 커스텀을 위해 수정이 필요할 것 같습니다. 세연님이 허락해주신다면 제가 변경해보도록 하겠습니다..!

Update: 요청 프롬프트  영어로 변경

---

src/Pages/Generate.tsx
src/Pages/Home.tsx
src/Pages/MyPage.tsx
src/services/uploadImageToFirebase.ts

1. 해쉬태그 firebase에 저장 후 MyPage에서 보여주는 기능 추가했습니다. 이미지를 날짜 시간 순서로 정렬했습니다.
2. Home페이지에서 `await getCountAndTimeLeft(userCredential.user)` 작업이 `setCurrentUser` 보다 먼저 작동하는지 횟수가 남았는데도 survey로 이동하지 않아서 `currentUser`대신 `userCredential.user` 전달해주는 것으로 수정했습니다.
> 마이페이지에서 이름 들어가 있는 부분은 이메일로 넣어놨습니다. 이름으로 하고 싶다면 회원가입에서 수정이 필요할 것 같습니다.

Feat: 해쉬태그 firebase에 저장 후 MyPage에서 보여주는 기능 추가 & Fix: 로그아웃 후 input값 남아있는 것 수정, getCountAndTimeLeft 인자값 변경

---

src/services/imageGenerator.ts

Update: 프롬프트 전신으로 수정

---

src/pages/Home.tsx
src/pages/Result.tsx

> #88
1. 로그인 시 home 페이지로 이동했다가 바로 survey로 이동하는 현상은 로그인 했을 때 count&limit 확인 여부 없고 mypage로 이동하는 것으로 수정했습니다.
2. 로그인 여부에 따라 결과 페이지의 버튼 다르게 보이지 않는 이슈 수정했습니다. loading을 추가해서 currentUser 설정이 된 후에 보여지게 했습니다.

Fix: 로그인에 따라 결과페이지 버튼 다르게 안보이는 이슈 수정, 로그인 시 mypage로 이동

---

package-lock.json
package.json
src/pages/Survey.tsx

Survey 문항이 넘어갈 때 애니메이션이 추가되었으면 좋겠다는 1차 피드백 의견을 반영하여, 페이지가 오른쪽으로 스와이프되는 효과의 애니메이션 로직을 추가하였습니다.

Feat: Survey 페이지 문항 넘어갈 때 스와이프 애니메이션 구현

---

src/pages/Generate.tsx
src/pages/Home.tsx
src/pages/MyPage.tsx
src/pages/Result.tsx
src/services/auth/loginWithEmail.ts
src/services/auth/loginWithGoogle.ts
src/services/auth/logoutService.ts
src/services/profileGenerator.ts
src/services/uploadImageToFirebase.ts

**1. 로그인 관련 로직들을 분리했습니다.** 
**2. firebase 구글 로그인 구현했습니다. 그리고 구글 로그인 user도 이미지 저장 및 관리가 필요하기 때문에 구글 로그인 성공하면 user 이메일을 firestore에 저장할 수 있도록 했습니다.**
- 기기나 플랫폼에서 가끔 팝업을 차단하는 경우가 있으며 모바일 사용자의 경우 흐름이 원활하지 않을 수 있어서 `signInWithPopup()` 대신에  `signInWithRedirect()`을 사용해서 구현했습니다.
- 그런데 리디렉션 로그인을 사용하기 위해서는 추가해야하는 사항이 있습니다. 기존에 vercel.json 파일에 api 요청 주소가 들어가 있는 것이 있어서, 권장사항 옵션들 중에서 프록시 설정하는 방법을 선택했습니다. 
> https://firebase.google.com/docs/auth/web/redirect-best-practices?hl=ko&_gl=1*103mtre*_up*MQ..*_ga*MzE2NTMyOTMzLjE3MjQ4MTk5NTY.*_ga_CW55HF8NVT*MTcyNDgxOTk1Ni4xLjAuMTcyNDgxOTk1Ni4wLjAuMA..
> https://firebase.google.com/docs/auth/web/google-signin?hl=ko&_gl=1*swf87h*_up*MQ..*_ga*MzE2NTMyOTMzLjE3MjQ4MTk5NTY.*_ga_CW55HF8NVT*MTcyNDgxOTk1Ni4xLjAuMTcyNDgyMTEyMi4wLjAuMA..
> …

Feat: 구글 로그인 구현, 이미지 관련 프로필 생성 로직 추가 Refactor: 로그인 관련 로직 분리

---

src/pages/Generate.tsx
src/pages/Survey.tsx
src/services/imageGenerator.ts
src/services/profileGenerator.ts

> 간헐적으로 프롬프트가 의도치 않게 변경되어 원하는 이미지가 불러와지지 않는 버그를 수정했습니다.
> 원인은 AI가 프롬프트를 이해하지 못할 경우 자신이 이해하기 쉽도록 내부 로직에 의해 프롬프트가 변경됩니다. 저희는 키워드만 나열하는 형식이라 AI가 프롬프트를 임의로 다시 만들어 이미지를 만들기 때문에 발생한 오류 같습니다.
> 따라서 AI가 선호하는 프롬프트를 그대로 가져와 리터럴 템플릿으로 데이터만 변경해주어 프롬프트가 최대한 변경되지 않도록 수정했습니다.
```
// 요청 프롬프트
prompt: "Create a realistic and passport-style image.  The subject is a Korean woman in her  30s with a muscular physique and a angular face. She  has tanned dark skin, distinguishing double eyelid eyes, and a bob cut with blonde hair. She  is wearing a sports style outfit. The image is set against a plain light-colored background with soft lighting, exuding a natural, polished, and refined look"
```
```
// 수정된 프롬프트
"revised_prompt": "Create a realistic passport-style image of a South Asian woman in her 30s with a …
```

fix: 프롬프트 버그 수정

---

src/pages/MyPage.tsx
src/pages/Result.tsx

> firebase의 DB 구조 개편에 따른 마이페이지 로직을 수정했습니다
> 이전 Generate 페이지 리팩토링을 할 때 resultUrl을 넣지 않아서 임의로 넣었습니다. 다르게 리팩토링이 가능하다면 수정 부탁드립니다!

refactor: mypage 로드

---

src/components/utils/Survey.ts

> 설문에 "상관 없음"을 추가했습니다.
> "상관 없음"은 평범한, 자연스러운과 같은 키워드들로 선택됩니다
> 문항이 많다고 판단하는 설문은 임의로 조정했습니다
`"revised_prompt": "Create a realistic, passport-style image of a Korean woman in her 20s with an average body physique and a non-makeup face. Her skin tone is natural, eyes are simple and distinguishing, and she has a straight, naturally colored hair cut. She is dressed in a simple, casual style outfit. The image background is plain and light-colored with soft lighting, which altogether gives a natural, polished, and refined look.",`

refactor: 설문 조정

---

src/components/functional/EmailVerificationModal.tsx
src/components/functional/FindPasswordModal.tsx
src/components/ui/Main.ts
src/components/ui/Modal.tsx
src/pages/Home.tsx
src/pages/SignUp.tsx

1. 홈페이지에 비밀번호 찾기 기능을 추가했습니다.
- firebase의 `sendPasswordResetEmail()`로 구현했습니다.
- 모달에서 이메일을 입력하고 발송 버튼을 클릭하면, 비밀번호 재설정 이메일이 발송됩니다.
- 이메일 내 링크로 비밀번호를 재설정 할 수 있습니다.
2. 모달 컴포넌트를 분리해서 비밀번호 찾기, 이메일 인증 모달로 사용했습니다.
3. 홈페이지 UI 피그마대로 반영했습니다.
- 피그마에서 홈페이지 디자인 보시면 비밀번호 찾기는 없지만 지난 회의 때 필요하다는 의견이 있어서 추가했습니다.
- 아이디 저장이 UI 디자인에 있던데, 이번 주에 얘기 나눠보고 필요하다고 판단되면 반영하겠습니다!

Feat: 비밀번호찾기 기능 추가, Refator: 모달 컴포넌트 분리 및 재사용, Fix: 홈페이지 UI 피그마 반영

---

src/App.tsx
src/components/ui/Loading.tsx
src/pages/Generate.tsx

1. 기존에 setTimeout 함수로 처리하던 progress bar 동적 UI를, 각각의 작업 전후로 업데이트 로직을 추가하여 작업 단계별 정확도를 반영하도록 리펙토링했습니다.
2. 기존 10%씩 건너뛰어 증가하던 progress bar 동적 UI를, 1%씩 점진적으로 증가하도록 `updateProgressSmoothly` 함수를 도입하여 사용자에게 더 부드러운 UI를 제공할 수 있도록 리펙토링했습니다.
3. 화면에 progress 퍼센트 텍스트가 없는 것이 좋을 것 같다는 정호님 의견을 반영하여 제거했습니다.
2-1. Generate 컴포넌트는 **(1)이미지 생성, (2)webP 변환, (3)이미지 관련 profile 생성, (4)Firebase에 이미지 및 프로필 저장, (5)사용자 문서 업데이트, (6)최종 progress 업데이트 및 결과페이지 이동** 총 6단계를 거쳐 실행됩니다. 
2-2. Chrome 개발자 도구 Network를 바탕으로 분석한 결과, (1)단계가 평균 10초 전후로 가장 많은 시간이 소요되고, 나머지 단계들의 속도 차이는 1000ms 미만으로 체감하기 어렵습니다.
2-3. 따라서 6단계의 progress 상태를 균등하게 분배하면 progress가 특정 구간에 오래 지연되어 사용자들에게 원활하지 못한 시각적 효과를 제공할 우려가 있습니다. 이에 보다 지연 없는 동적 progress UI를 제공하기 위해 **(1)단계가 실행되는 동안 progress가 50%에 도달**하도록 설정했습니다.
2-4. `updateProgressSmoothly` 는 타깃 progress와 타깃 …

Refactor: Generate progress 업데이트 로직 단계별 정확도 반영, 점진적 퍼포먼스 개선

---

src/components/ui/Header.tsx
src/pages/MyPage.tsx
src/pages/Result.tsx

1. Header 컴포넌트에 로그인 여부를 판별하여 로그인/로그아웃 버튼이 나타나도록 수정했습니다.
2. Header 컴포넌트에 로그아웃 로직을 추가했습니다.
3. Result, Mypage에 Header 컴포넌트 추가했습니다.
헤더 UI는 오늘 회의 때 논의해보고 수정하면 좋을 것 같습니다.

Feat: header 로그인여부 판별로직, 로그아웃 추가 / Fix: 페이지 header 추가

---

src/components/ui/Dropdown.tsx
src/pages/Generate.tsx
src/pages/MyPage.tsx

> 정렬 드롭다운 컴포넌트를 생성했습니다. 레이아웃 위치는 마이페이지 디자인 완성되는대로 수정 예정입니다
> 이미지를 새로 생성하면 이제 최신순으로 정렬됩니다

feat: 정렬 드롭다운 생성, refactor: 이미지 최신 순 저장

---

src/pages/Home.tsx
src/services/auth/loginWithEmail.ts
src/services/auth/loginWithGoogle.ts

> 홈페이지에 기존에 팝업으로 구현해놓은 구글 로그인 기능을 다시 넣었습니다.
> 이메일 로그인도 분리해놓은 것이 있어 홈페이지에 반영했습니다.

Fix: Home 페이지에 구글 로그인 기능 다시 넣음

---

.husky/_/post-commit
.husky/_/post-merge
.husky/_/pre-commit
.husky/_/pre-push
package.json

> husky pre-commit까지 적용하여 lint-stage도 자동으로 되게끔 설정했습니다.
> prepare를 삭제하여 husky가 초기화되지 않게 설정했습니다. 
- 혹시 모르니, pre-pare의 husky install 구문을 지우고 pull 받으시면 원활하게 진행될 것입니다.
- 현재 main branch에 새로운 yml파일을 만들었습니다. sync-fork 자동 CI/CD 구축 및 테스트 중입니다. 성공하면 다시 말씀드리겠습니다~!

fix: husky settings

---

package-lock.json
package.json
src/components/ui/header.tsx
src/components/ui/loading-screen.tsx
src/pages/generate.tsx
src/pages/result.tsx

#127 
> generate 페이지 로딩 UI를 개선했습니다.
- **작동방식** : `generate` 페이지 작업 속도에 맞춰 점진적으로 증가하는 progress bar를 보여주었습니다.
- **문제** : `generate` 페이지에서 이루어지는 작업 속도가 각기 달라 progress bar가 일시적으로 멈추거나 일관되지 않은 증가율을 나타내는 등 사용자 경험을 저하시키는 문제가 있었습니다.
- **작동방식** : 로딩 spinner을 화면 중앙에 배치하고, spinner 하단에 3초마다 변경되는 텍스트를 삽입했습니다.
- **효과** : progress bar를 완전히 제거하여 사용자가 작업 속도를 인지할 수 없어, 로딩 대기시간을 덜 지루하게 느낄 수 있습니다. 또 주기적으로 바뀌는 텍스트는 예측 가능한 동적 UI를 제공함으로써 사용자 경험을 높일 수 있습니다.
- **추가한 라이브러리** : React 컴포넌트 안에서 간단한 문법으로 애니메이션을 정의할 수 있는 라이브러리인 `Framer Motion`을 설치했습니다. 작성한 코드처럼 `<motion.p>` 태그 내부에 지속 시간, 지연 시간 등을 사용해 애니메이션을 커스터마이징할 수 있습니다.
- 추가로 css 마이그레이션 후 header 컴포넌트에서 로그아웃 | 마이페이지 영역이 수평이 맞지 않아 불필요한 태그를 제거하고 margin 수정했습니다.
https://github.com/user-attachments/assets/9e43f14a-64d9-411d-8b8b-a9ed620b0687
> generation 로직 개편 후 생성 속도가 …

Refactor: generate 로딩 UI 개선

---

src/components/ui/button/button-group.tsx
src/components/ui/button/button.tsx
src/components/ui/flexbox.tsx
src/components/ui/header.tsx
src/components/ui/main.tsx
src/components/ui/text.tsx
src/pages/home.tsx

> PR에서 바로 진행하기에 좀 어려워서 일단 pull을 받고 코드리뷰를 진행했습니다
> 변경사항이랑 주석 확인해보시면서 저랑 의견이 상이하거나 이해가 안되시는 것 있으시면 꼭 말씀해주세요!

review: tailwind 마이그레이션 코드 리뷰

---

package-lock.json
package.json

> #150
> styled-components 삭제했습니다.

Refactor: CSS 마이그레이션에 따른 styled-components 삭제

---

.github/workflows/sync-fork.yml
src/services/auth/login-with-email.ts

> 유효하지 않은 로그인 입력 시 콘솔로 입력되던 부분을 alert창을 띄워 명시적으로 보여주는 예외처리를 추가했습니다.
> sync-fork 자동 로직도 추가했는데 테스트용이라 신경 안쓰셔도 됩니다!

fix: invalid login or password 예외처리 

---

package-lock.json
package.json
src/components/functional/find-password-modal.tsx
src/components/ui/error-message.tsx
src/components/ui/input.tsx
src/components/utils/validation.ts
src/pages/home.tsx
src/pages/signup.tsx

> 커스텀 Input을 사용하는 모든 페이지의 유효성검사와 form 제출을 zod, react-hook-form라이브러리를 사용해 리팩토링 했습니다.
> `zod`, `react-hook-form`, `zodResolver`라이브러리 설치했습니다.
> 일일이 유효성 검사하지 않아도 되고, onChange, value를 일일이 넣어주지 않는것이 아주 편하고 보일러플레이트 코드가 주는 것을 체감했습니다~!
> Input의 color값이 적용이 안되는 버그가 있습니다.
> Text만 동적으로 할당이 안되는 것 같습니다.
그리고 code rabbit이라는 pr을 관리해주는 AI를 한번 도입해봤습니다.
https://velog.io/@heyday_xz/AI-%EC%BD%94%EB%93%9C%EB%A6%AC%EB%B7%B0-%EB%B6%99%EC%97%AC%EB%B3%B4%EA%B8%B0
관련 포스팅이니 한번 읽어보세요~

refactor: 유효성검사 zod,react-hook-form 으로 리팩토링

---

src/components/functional/convert-to-webp.ts
src/components/functional/error-boudary.tsx
src/components/functional/kakao-share.tsx
src/contexts/auth-context.tsx
src/pages/mypage.tsx
src/pages/result.tsx
src/services/auth/login-with-google.ts
src/services/save-result-url-to-firebase.ts

> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

fix: console문 삭제
