what-is-your-ideal-type/FE_what-is-your-ideal-type

src/Pages/Home.tsx, src/components/Button.tsx, src/components/ButtonArgs.ts
> 버튼 타입 에러가 발생해서 타입을 분리하고 확장했습니다.
> ButtonArgs에 타입을 지정해주지 않아서 생긴 에러로 StyleProps라는 타입을 지정하고 ButtonProps에 type과 label을 확장해서 넣어주었습니다.
> Home에서 '로그인 없이 시작' 클릭 시 survey로 이동하게 지정했습니다. 그에 따른 Button에 onClick 타입도 지정해주었습니다.
=> Fix: 스타일 타입 지정 및 확장 / Feat: Home => Survey 라우터 설정 및 타입 추가

src/Pages/Result.tsx, src/Pages/Survey.tsx, src/components/Loading.tsx, src/index.tsx, src/services/imageGenerator.tsx
> survey 페이지에서 설문조사 한 정보들을 토대로 AI 요청을 보내고 불러오기 기능을 구현했습니다.
> Loading.tsx 컴포넌트가 선언문으로 되어있어 표현식으로 변경했습니다.
> 요청이 대략 13초정도 걸리는데, setTimeout을 15초 정도로 해도 좋을 것 같아요!
> 내일은 survey를 변경해서 좀 더 실사적으로 이미지를 뽑아보죠
=> Feat: survey => result ai 요청 결과 불러오기 / Fix: Loading.tsx 컴포넌트 함수 표현식으로 변경

src/Pages/Result.tsx, src/firebase.ts, src/services/uploadImage.ts
> 결과 페이지에서 imageUrl을 받아서 storage에 업로드하고 접근할 수 있는 downloadUrl을 리턴하고 있습니다.
> 비회원 사용자와 회원 사용자 모두를 고려한다면 firestore + storage 둘 다 사용하는 것이 적절한 저장소를 제공할 수 있다고 판단됐고, 로그인 한 경우 firestore에 downloadUrl을 저장하는 것은 완료되는 대로 올리겠습니다.
=> Feat: 생성 이미지 storage 업로드

package.json, src/services/uploadImage.ts
> #48 
> Proxy로 CORS오류를 해결했습니다
> Proxy로 이미지 도메인을 지정하고 이미지 url을 해당 도메인만큼 문자열에서 지워주었습니다
> 결과로 proxy는 잘되어 업로드가 잘 되는 것을 확인했습니다 
> vercel은 따로 지정해줘야 합니다
> @sennydayk 세연님 배포시에 vercel.json 생성하셔서 복붙하시면 될 겁니다!
```json
// vercel.json
{
"rewrites": [
{
"source": "/api/:path*",
"destination": "https://oaidalleapiprodscus.blob.core.windows.net/:path*"
}
]
}
```
=> Fix: CORS오류 proxy로 해결

src/components/Button.tsx, src/components/ButtonArgs.ts
> #58 
> styled-components로 prop을 내릴때 생기는 경고로 DOM이 해당 값을 읽을 수 없다고 합니다.
> prefix '$'을 앞에 붙여 해당 porp을 styled-components 내에서만 사용하게 합니다. 
> 경고만 있는거지만, 후에 Light House 점수에 영향을 미칠 수 있다고 생각해 조치를 취했는데 괜찮을까요? @sennydayk 님이 작성하신 props라 컨펌 해서 머지해주시면 됩니다.
=> Fix: React props Warning 제거

src/Pages/MyPage.tsx, src/Pages/Result.tsx, src/firebase.ts, src/services/uploadImage.ts
> 로그인을 하고 이미지를 만들었을 경우 uid를 확인하여 해당 유저의 firestore 컬렉션에 저장하는 것을 작업했습니다.
> uid를 확인하고 해당 유저의 firestore에 있는 이미지를 mypage에서 볼 수 있게 했습니다.
> openAI API가 제공하는 url이 지속성이 낮기 때문에, 비로그인이든 로그인이든 생성된 이미지를 storage에 넣은 이미지에 넣고 firebase에서 제공하는 downloadUrl을  firestore에 넣고 있습니다.
=> Update: 이미지 저장(로그인, 비로그인 구분해서 저장) / Feat: myPage에서 해당 유저의 firebase 이미지 보여주기

src/services/convertToWebP.ts
> #62 
> 이미지 해상도가 1024x1024로 사용되는 이미지보다 과도하게 해상도가 높은 것을 확인했습니다.
> canvas로 이미지를 그릴 때 절반인 512x512로 이미지로 해상도를 낮췄습니다.
> `toBlob`의 매개변수인 quality를 0.5로 설정해서 기본 화질의 50% 품질 저하를 일으켰습니다.
> 용량과 속도가 50%씩 절감 되었습니다.
> LightHouse Performance 부분도 50% => 56%로 증가했습니다.
=> Update: 이미지 해상도 및 품질 다운그레이드

src/App.tsx, src/Pages/Generate.tsx, src/Pages/Result.tsx, src/Pages/Survey.tsx, src/components/Loading.tsx, src/components/Picture.tsx
> #69 
> 리액트는 CSR로 최초 진입 시 모든 번들 파일을 다운받아 이후에 빠르게 동작합니다. 하지만, 최초에 모든 파일을 다운 받으려 하니 초기에 느릴 수 있습니다.
> 이를 해결하기 위해 lazy 함수로 번들 사이즈가 큰 페이지는 진입시에 번들 파일을 다운 받게끔 하여 최초 진입 시에는 진입하지 않은 페이지의 파일들을 다운받지 않습니다.
> 번들 파일들을 분석해보니 firebase 모듈러가 가장 큰 용량을 차지했기에 firebase를 사용하는 페이지는 모두 lazy처리 했습니다.
>img 태그에 picture 태그, source태그를 확장해서 붙이면 LightHouse점수가 오르는것을 보고 Picture 컴포넌트로 확장해 만들어 봤습니다 img는 이 컴포넌트를 쓰면 렌더링에 용이할 것 같습니다!
> 프로젝트가 소규모라 엄청 큰 체감은 없지만 performance가 5% 상승했습니다!
=> Update: 코드 스플리팅: lazy, suspsnse / img 태그 Picture 컴포넌트로 확장

src/Pages/Generate.tsx, src/Pages/Result.tsx, src/components/Picture.tsx, src/services/uploadImageToFirebase.ts
1. 사진 저장 아이콘을 클릭하면 이미지 파일이 바로 다운로드 되게 하기 위해 `a` 태그에 `download` 속성을 설정하였지만, 여전히 이미지가 새 창에서 열리는 문제가 있었습니다.
서버에서 `Content-Disposition: attachment` 헤더를 설정하여 해결할 수 있지만, 클라이언트 측만을 사용하는 경우엔 이를 설정 하기 어렵기 때문에 강제로 다운로드 트리거하는 방법을 사용했습니다. 
현재 사진 저장 아이콘을 클릭하면 이미지 파일이 바로 다운로드됩니다.
2. 사진저장 아이콘이 따로 있으므로, 결과 페이지에서 보여주는 이미지의 우클릭, 드래그 기능을 방지했습니다.
> 2번 관련해서는 Picture.tsx Image에만 추가했는데, 혹시 모든 페이지에서 동일한 기능이 필요하다고 판단된다면 App.tsx에 추가하면 좋을 것 같습니다.
=> Update: 사진 저장 버튼 클릭시(새창열림->바로 다운로드), Feat: 결과 이미지 우클릭과 드래그 방지

src/Pages/Generate.tsx, src/Pages/Home.tsx, src/Pages/MyPage.tsx, src/components/NavigateToSurvey.tsx, src/services/countService.ts
> 이미지를 생성할 수 있는 횟수를 제한하는 작업을 했습니다. 로그인한 경우에는 firebase에 count와 갱신 날짜를 저장해서 사용했고, 비로그인인 경우에는 localStorage로 사용했습니다.
> survey 버튼 클릭 시 count, limit 확인 후 navigate하기 위해 컴포넌트를 추가했습니다.
- 현재 로그인 시 제한 횟수 3회, 비로그인시 제한 횟수 1회로 해놓았습니다. 횟수는 의논해보고 수정해도 될 것 같습니다.
- 이미지 생성 횟수 초과하고 갱신 시간이 지나지 않았는데 재로그인한 경우에 survey로 바로 이동 안되게는 해놨으나, 웹 주소창에 `/survey`로 입력해서 접근한 경우에는 가능한 상태입니다. 이 부분은 수정이 필요해 보입니다.
=> Feat: 이미지 생성 횟수 제한, survey 페이지 이동 버튼 컴포넌트 추가

src/pages/Result.tsx
Result 페이지에서 로그인 여부를 제대로 판별하지 못하는 버그를 수정했습니다. 
기존에 상태 판별 값으로 사용하던 currentUser은 객체로 반환되기 때문에 currentUser.currentUser로 접근해야 null값으로 가져올 수 있습니다.
=> Fix: Result 페이지 로그인여부 판별 로직 수정

src/components/Picture.tsx, src/components/PreventDefaultWrapper.tsx, src/pages/Generate.tsx, src/pages/MyPage.tsx, src/pages/Result.tsx, src/services/saveResultUrlToFirebase.ts, src/services/uploadImageToFirebase.ts
1. user인 경우 firestore images 컬렉션에 결과 페이지 url을 저장하는 코드를 추가했습니다. 마이페이지에서 해당 생성 사진의 결과 페이지로 이동 가능하게끔 했습니다.
2. 바로 다운로드 기능 모바일에도 가능하게 수정했습니다.
3. 생성된 이미지에만 적용했던 기본 기능 방지가 아이콘에도 드래그, 우클릭, 터치 기능을 방지하는 것이 필요하다고 판단됐고, 관련 코드를 컴포넌트로 만들어서 사용했습니다.
1. 마이페이지에서 각 카드 전체를 영역으로 잡아서 클릭 이벤트를 넣었는데 사진에만 적용하면 좋을지 의논해보면 좋을 것 같습니다.
2. 제 핸드폰으로 테스트해보니 모바일에서는 바로 다운로드가 안되고 있었습니다. iOS 기기에서는 a 태그를 통해 파일을 다운로드하는 방식이 제한적일 수 있다고 합니다. 그래서 canvas를 사용해 수정해놓았습니다. 
그런데 이 방법이 모바일이 최신 버전인 경우에만 적용 가능한 방법일 수 있어서 배포 환경에서 테스트 진행 후에 수정 여부를 봐야할 것 같습니다. 수정이 필요하다면 아마도 라이브러리(file-saver)를 사용해야할 것 같습니다.
=> Feat: 마이페이지에 결과페이지 url 추가, Update: 바로 다운로드 기능 모바일에도 가능하게 수정

src/components/Button.tsx, src/components/Survey.ts, src/pages/MyPage.tsx, src/services/imageGenerator.ts
> 모바일 환경에서 Survey 페이지의 버튼을 눌렀을 때 같은 위치의 버튼이 다음 페이지에서 hover되는 버그
> 해당 버그는 ios에서만 일어나는 버그입니다. 저는 android 유저라 테스트 했을 때 이상 없었는데, 생각해보니  제가 시행한 테스터들도 ios유저라서 발생한 버그인 것 같습니다.
> 사실 hover라는 이벤트가 마우스가 있는 환경 즉, 데스크톱에서만 가능한 이벤트인데, ios는 UX를 증가 시킬 목적으로 hover를 비슷하게 구현했다고 합니다. 따라서 이와 같은 버그가 발생한 것 같습니다
> 많은 해결책이 있는데 그 중 active라는 속성으로 테스트를 진행해볼 예정입니다. active는 터치나 클릭이 일어났을 때 발생하는 이벤트로 터치가 발생하면 hover되기 전 색상 즉, 원래의 색상을 그대로 덮어 씌웁니다. 따라서 모바일에서는 hover와 active가 동시에 일어나므로 cascading으로 인해 active로 씌워질 것으로 기대됩니다.
> 이 외에는 미디어 쿼리를 이용해 없앨 수 있습니다. 방법은 많으니 이번 테스트가 안된다면 다른 방법으로 시도해보겠습니다.
```css
a:hover { /* default hover effect */
color: black;
background: yellow;
}
@media (hover: hover) { /* when supported */
a:hover {
color: white;
background: black;
}
}
```
=> test: 아이폰 테스트

src/components/Button.tsx, src/components/Survey.ts, src/pages/MyPage.tsx, src/services/imageGenerator.ts
> 설문 결과가 실사처럼 안나오는 이슈가
- `korean`으로 명시하여 구체적인 프롬프트를 전달했습니다
- 세부적인 키워드들을 조금 조정했습니다
- gpt4를 통해 dall-e 모델이 실사로 만들 수 있는 프롬프트 키워드들을 학습하여 적용했습니다 `(fixPrompt)`
- 특히 `passport-style`이라는 키워드에는 유독 실사처럼 보여주어 더욱 높은 퀄리티를 제공합니다
- 키워드를 공백으로 나눠 요청하면 dall-e가 따로 의역해서 이미지를 생성했는데 `,`로 구분하니 키워드 대로 그려줍니다.
- 유독 전신샷 혹은 상반샷은 다수의 사람을 보여주던가 그림티가 너무 나는 이미지만 보여주어 적용을 못했습니다.
- 가끔 대한민국 국기를 그린다던지, 카메라 앵글을 그린다던지 하는 오류가 있지만, 인물들은 대체로 완성도 높게 보여주는 것을 확인했습니다!
==============================================
- 실수로 PR을 한꺼번에 해버려서 취소하고 다시 PR올립니다!
=> refactor: AI 요청 프롬프트 수정

src/pages/Result.tsx, src/services/profileGenerator.ts
> 요청한 prompts를 json string형식으로 응답받고 JSON.parse()로 JSON형태로 가공하여 다시 사용하게끔 수정했습니다.
> location으로 profile들을 받고 있어 공유시에는 데이터를 제대로 읽어오지 못하는데 firebase를 개편하면서 한번 수정해보도록 하겠습니다.
> 현재는 유저 컬렉션만 운용중이고 유저 컬렉션에 게시물 정보들을 저장하는 형식인데 이를 개편해보겠습니다.
> 전체 게시물 컬렉션을 추가해서 해당 게시물의 정보 (이미지, profile 등)을 넣어주고 게시물에 id값을 부여해 id값을 추적하고 유지보수 하도록 계획중입니다.
> 추후에 진행해보고 올려드리겠습니다!
=> fix: 응답 prompts JSON으로 변경

craco.config.js, package-lock.json, package.json
#109 
src/ 디렉토리 외부에서 파일이 직접 import 되면서 로컬에서 npm start가 실행되지 않고 에러가 발생하는 문제가 있었습니다.
해당 모듈의 위치를 직접 변경하거나 별도의 symlink를 추가하는 것은 리액트 내부와 브라우저 간 충돌 문제가 우려되어, craco를 설치하여 기존 CRA의 설정을 커스텀하는 방법으로 문제를 해결하였습니다.  
**∙ CRACO 사용 이유**
create-react-app(CRA)은 기본적으로 프로젝트의 설정 파일(예: Webpack, Babel 등)을 직접 수정할 수 없게 되어 있어, 설정을 변경하려면 이를 우회하는 도구가 필요합니다. CRACO는 이러한 제약을 해결하기 위해 설정을 확장하거나 덮어쓸 수 있게 해줍니다.
CRA는 기본적으로 보안상의 이유로 외부 모듈을 import하는 것을 지원하지 않습니다. 외부 모듈을 효율적으로 사용하려면 특정 설정을 수정해야 하는 경우가 있는데, 이를 위해 CRACO를 사용하면 CRA의 기본 설정을 덮어씌울 수 있습니다.
https://github.com/dilanx/craco/blob/main/packages/craco/README.md#installation
https://blueprint-12.tistory.com/m/395
https://gorani-memo.ghost.io/create-react-app-cra-eseo-oebu-module-import-hal-su-issge-seoljeong-byeongyeonghagi/ (craco 활용 예시는 아니지만 외부 모듈 import 문제 발생 시 해결가능한 비슷한 …
=> Fix: craco 설정, 외부 모듈 import 에러 해결

src/pages/Generate.tsx, src/pages/Result.tsx
generate 페이지와 result 페이지에서 뒤로가기를 방지하는 기능을 추가하였습니다.
`window.history.pushState()` : 브라우저 히스토리 스택에 새로운 URL을 표시하여 새로운 페이지도 이동한 것처럼 보이는 API입니다. 그러나 실제 페이지는 리로드되지 않고 URL만 변경됩니다.
마이페이지 -> 결과페이지 뒤로가기도 방지하는 것이 좋을까요? 
어차피 마이페이지에서 결과페이지로 이동이 가능해서 따로 설정하지 않았는데 필요하다고 생각되시면 말씀해주세요!
=> Refactor: generate, result 페이지에서 뒤로가기 방지 기능 추가

src/App.tsx, src/pages/Generate.tsx, src/pages/Result.tsx, src/services/profileGenerator.ts, src/services/uploadImageToFirebase.ts
> 전에 설명드린것과 같이 Firebase에 DB 구조를 변경하면서 로직을 변경했습니다.
- posts에는 숫자로 각 post에 id가 부여됩니다.
- 각 post에 필요한 정보가 담깁니다.
- users에는 각 user의 uid로 문서가 생성되고 작성한 post의 id는 postList 필드에 저장됩니다.
- 마이페이지를 렌더링 할 때 이 user의 post정보들을 토대로 렌더링 됩니다.
> DB 구조 변화에 따른 users 컬렉션의 images 컬렉션을 삭제를 고려중인데 필요하신 데이터가 있으시면 말씀해주세요!
=> refactor: firebase DB 구조 변경에 따른 로직 변경

src/components/functional/EmailVerificationModal.tsx, src/components/ui/Button.tsx, src/components/ui/Text.ts, src/components/utils/ColorMap.ts, src/components/utils/Validation.ts, src/pages/SignUp.tsx, src/services/auth/signupWithEmail.ts
1. 유효성 검사 추가했고, 유효성 검사 로직과 firebase 관련 회원가입 로직을 분리했습니다.
2. 버튼 활성화 구현에서 hover가 없는 회색컬러가 필요해서 ColorMap > "disabled" 추가했습니다.
3. 회원가입 후 이메일 인증 로직 추가했습니다.
3-1. 처음에 진행하려고 했던 흐름은 이메일 인증 후 회원가입을 완료하는 것이었습니다.
3-2. 그러나, firebase에서 제공하는 인증 방식에서는 원하는 로직을 구현하기 어려웠습니다. firebase에서 제공하는 메서들 중 저희 프로젝트에 적용해볼 수 있다고 판단되는 메서드들입니다.
- `createUserWithEmailAndPassword` : 인증 절차 없이 이메일과 비밀번호로 바로 회원가입 가능한 방식입니다. 기존에 이 방식만 적용하여 구현한 상태였습니다. 
- `sendSignInLinkToEmail` : 회원가입용이라기 보단, 이메일 링크를 통해서 비밀번호 없이 로그인하는 방식입니다. 
- `sendEmailVerification` : 회원가입을 완료한 이메일이 유효한 이메일인지 인증하는 메서드입니다. 해당 메서드를 사용하기 위해서는 회원가입을 먼저 완료해야 합니다.
3-3. 사용자 몰래 이메일만 임시로 저장하고 그 이메일을 인증하는 방식으로 구현할 수는 있으나, 사용자에게 투명하지 않고 보안상 문제가 될 수 있을 것이라고 생각했습니다.
3-4. 사용자의 경험을 최대한 고려해서 선택한 방식은 회원 가입 후 이메일 인증을 모달로 처리하는 것입니다.
- 회원가입 절차는 빨리 끝내고 인증 후 서비스를 이용할 수 있게 했습니다.
- …
=> Feat: 회원가입 이메일 인증 로직 추가, Refactor: 유효성 검사 및 firebase 회원가입 로직 분리

src/components/functional/NavigateToSurvey.tsx, src/pages/Home.tsx, src/pages/SignUp.tsx
> 홈페이지에 원래 있었던 로그인 없이 시작 버튼을 다시 넣었습니다.
> '로그인 없이 시작' 버튼의 디자인을 '로그인하기' 버튼과 동일하게 만들어놨어서 일단 '로그인하기' 버튼 밑에 배치해뒀습니다. 근데 조금 이상하게 보여서 금요일에 디자인 및 위치 재조정에 대해 논의할 필요가 있을 것 같습니다!
=> Fix: 홈페이지에 '로그인 없이 시작' 버튼 다시 추가

src/components/ui/Header.tsx
> #126 
> Header 컴포넌트에 '홈' 버튼을 삭제하고 '로그인', '로그아웃' 만 구분되게 수정했습니다.
> DeskTop과 Mobile로 나누었었는데, 불필요 하여 통합하였습니다.
> 버튼 반응형을 구현했습니다.
=> refactor: Header 홈 버튼 빼기

package-lock.json, package.json, src/pages/MyPage.tsx
> #129 
> `useInfinityQuery`로 무한 스크롤을 구현했습니다.
> image 로딩 시 스켈레톤 이미지를 띄워 css가 깨지지 않게 조정했습니다.
> 최신순, 오래된 순을 잠시 보류했습니다.
- 무한 스크롤
---
- 스켈레톤 이미지 전
- 스켈레톤 이미지 후
- 정렬(최신순, 오래된 순)에 고민이 있어 잠시 로직을 삭제했었는데, 정렬 방식을 선택하면 전체를 리렌더링하여 스크롤을 상단으로 돌리게끔 구현하도록 하겠습니다.
- 전체적으로 데이터 패칭 전에 컴포넌트가 순간적으로 렌더링되는 현상을 잡아야될 것 같습니다. (특히 마이페이지, 결과 페이지)
=> feat: 무한 스크롤 구현

.github/workflows/main.yml, .gitignore, package-lock.json, package.json, src/components/functional/KakaoShare.tsx, src/components/functional/convertToWebP.ts, src/components/ui/Header.tsx, src/components/ui/Text.ts, src/components/utils/ColorMap.ts, src/pages/Generate.tsx, src/pages/MyPage.tsx, src/pages/Result.tsx, src/services/auth/loginWithGoogle.ts, src/styles/styled.ts, vercel.json
1. **마이페이지, 결과페이지 UI 피그마 반영해서 수정했습니다.**
2. **generation 컴포넌트에서 `currentUser` 유무에 따른 선택적 firebase 문서 업데이트 로직으로 수정했습니다.** 로그인된 사용자 없이 이미지가 생성될 경우, posts 컬렉션에는 `userId`와 `email`이 `null`로 업데이트되고, users 컬렉션은 업데이트되지 않습니다.
로그인 없이 이미지 생성을 시도할 경우, 수정한 UI가 반영되지 않는 문제가 있습니다. styled-componenets 사용 시 스타일 속성을 DOM 요소로 직접 전달하면 발생하는 에러로, 예정된 tailwindcss 마이그레이션을 진행하면 해결될 문제로 보입니다.
=> Fix : 마이페이지, 결과페이지 UI 수정 / generation에서 currentUser 유무에 따른 선택적 firebase 문서 업데이트 로직 수정

.husky/_/post-merge, .husky/_/pre-push, src/components/functional/convert-to-webp.ts, src/pages/Generate.tsx, src/pages/Result.tsx, src/pages/Survey.tsx, vite.config.ts
> **vite proxy 설정으로 cors 에러를 해결했습니다.**
vite 마이그레이션 후, 로컬 개발모드에서 이미지 생성 요청 도중 webP 변환 과정에서 중단되는 문제가 있었습니다. 문제 분석 결과, `convert-to-webP` 로직에서 다시 패치한 url 주소가 cors 정책에 의해 접근이 불가능함을 확인했습니다.
이에 `vite.config.ts` 파일에 프록시 설정을 추가하고, `convert-to-webP` 로직에서 `baseUrl`를 설정해 개발 모드와 배포 모드에서 각기 다른 주소로 요청을 보내도록 수정했습니다.
=> Fix: vite proxy 설정

src/components/functional/navigate-to-survey-props.tsx, src/hooks/use-guest-mode.ts, src/pages/Generate.tsx, src/pages/Home.tsx
> useGuestMode라는 훅으로, 로그인 없이 사용하는 유저를 판별하는 로직을 만들었습니다.
> `useSyncExternalStore`라는 훅을 사용해 로컬 스토리지를 리액트의 상태처럼 관리할 수 있습니다.
> 해당 결과물은 anonymous_posts라는 DB에 저장됩니다.
> 원활한 작업을 위해 `progressbar`을 로직에서 제거했습니다.
- 현재는 '로그인 없이 시작하기'를 누르면 `guestMode: true`로 설정됩니다. 그 후 survey에서 한번 더 guestMode인지 확인 후 저장 할 DB를 나눕니다. 
- 더 나은 방향이 있을 것 같은데 아직 잘 모르겠습니다. 수요일날 혹시 좋은 의견 있다면 공유 부탁드립니다.
- 해당 훅은 리액트 외부 (session, localstorage 등)의 상태들을 리액트의 상태처럼 등록하여 리액트의 상태변화처럼 컴포넌트를 리렌더링 시킨다는 메커니즘인데, 이 프로젝트에서는 localstorage를 굳이 상태로 관리해야할까? 라는 의문이 생겼습니다. 로컬 스토리지로 이루어지는 인터렉션이 없기 때문입니다.
- 물론 커스텀 훅으로 사용되어 재사용성이 높고 보일러 플레이트 코드가 줄어든다는 것이 장점인데 해당 고민이 있어 다른분들은 어떻게 생각하실지 의견 나눠보고자 글 남깁니다...!
=> feat: useGuestMode

src/components/ui/text.tsx
> tailwind 공식문서에서 props를 사용하여 클래스 이름을 동적으로 작성하지 말라고 명시되어 있었습니다.
> 따라서, 기존 코드와 일관성 있게 객체를 활용하여 props를 정적 클래스 이름에 매핑하도록 수정하였습니다.
1. 해당 내용이 명시된 공식문서 링크 첨부했습니다.
> https://tailwindcss.com/docs/detecting-classes-in-source-files
2. 회원가입에서 유효성검사 에러가 잘 적용되는지 확인하는 과정에서, 현재 input에 입력시 실시간으로 에러 표시해주지 않고 form 제출 버튼을 클릭했을 때 에러 표시해주는 것으로 확인했습니다. 
사용자 관점에서 실시간으로 에러 표시해주는 방향을 고려해봐도 좋을 것 같습니다!
`mode: 'onChange'` 를 추가하면 실시간으로 에러 표시 가능합니다.
=> fix: text color 템플릿 리터럴 적용 안되는 버그 해결

src/App.tsx, src/components/ui/header.tsx, src/components/utils/cookies.ts, src/components/utils/post-migration.ts, src/pages/generate.tsx, src/pages/result.tsx, src/services/auth/login-with-email.ts, src/services/auth/login-with-google.ts, src/services/auth/logout.ts
> 기존에 generate에서 모두 처리하던 이미지 변환 및 Firebase 저장 로직을 일부 result에서 처리하도록 개편했습니다. 게스트 모드인 경우, result 페이지 비동기 작업 말미에서 쿠키에 `postId`를 저장하는 로직을 구현했습니다. 로그인 시 쿠키 `postId` 유무를 판별하여 해당 데이터를 사용자 계정으로 자동 이전하는 기능을 구현했습니다.
**`generate.tsx`**
- 이미지와 프로필 생성 작업만 수행하고, 생성된 결과를 그대로 result 페이지로 넘기도록 수정했습니다.
- 이미지 생성과 프로필 생성은 생성 시간 단축을 위해 병렬 작업으로 처리했습니다.
**`result.tsx`**
- 기존에 generate에서 수행하던 이미지 WebP 변환, Firebase 작업을 result 백그라운드에서 처리하도록 수정했습니다.
- 백그라운드 작업 시, 해당 postId가 기존 firebase 컬렉션에 존재하는지 검증 후 새 데이터를 저장하도록 로직의 안정성을 높였습니다.
- 쿠키에 저장된 `GUEST_MODE` 값을 판별하여 게스트/로그인 모드에 따른 분기 처리를 하도록 수정했습니다.
- `GUEST_MODE`가 `true`인 경우, 생성된 `postId`를 쿠키에 저장하도록 구현했습니다.
- 만약 기존 쿠키에 postId가 존재하는데 게스트 모드에서 다시 이미지를 생성할 경우, 쿠키는 새로 생성된 `postId`로 값이 덮어씌워집니다. (게스트 모드는 카운트가 1번이기 때문에 이 경우는 딱히 신경쓰지 않아도 될 것 같습니다.)
- 쿠키 관리 관련 로직을 …
=> Refactor: generate 로직 개편, result 로직 분기 개편 / Feat: 로그인 시 데이터 마이그레이션 로직 추가

src/components/ui/button/button.tsx, src/components/ui/header.tsx, src/components/ui/main.tsx, src/components/ui/text.tsx, src/hooks/use-responsive.ts, src/pages/home.tsx, src/pages/result.tsx
> #150
- Main 컴포넌트 사용 시, isMobile을 props로 받지 않고 컴포넌트안에서 tailwind 코드로 반응형 적용했습니다.
- use-responsive.ts 삭제했습니다.
- 홈페이지에서 가입하기 버튼 밑줄에 라운드가 들어있어서 underline button: border-radius none으로 수정했습니다.
> text 컴포넌트는 매번 뷰포트 크기에 따라 사이즈가 바뀌는 것은 아니기 때문에 isMobile을 대체하는 것에 고민이 있었습니다. tailwind는 기본적으로 모바일 크기로 반응형 코드를 제공하기 때문에 props로 `desktopFontSize`을 추가하여 전달하는 방식으로 변경했습니다. 혹시 다른 방법이 있다면 공유 부탁드립니다!
=> refactor: isMobile 대신 tailwindCSS 코드로 변경

src/components/utils/post-migration.ts, src/pages/mypage.tsx, src/services/auth/login-with-google.ts, src/services/auth/logout.ts
> 마이페이지에서 로그아웃 시 곧바로 홈으로 리다이렉트되지 않고 새로고침해야 하는 버그를 해결했습니다. 불필요한 `console.log` 디버깅 코드를 제거했습니다.
- 마이페이지에서 로그아웃 시, 콘솔창 에러와 함께 홈으로 곧바로 리다이렉트되지 않는 버그가 있었습니다.
- 마이페이지 컴포넌트가 렌더링되는 도중에`BrowserRouter`의 상태를 업데이트하려고 시도했기 때문에 에러가 발생했습니다.
- React는 한 컴포넌트의 렌더링 중에 다른 컴포넌트의 상태를 변경하는 것을 허용하지 않습니다.
- 마이페이지 컴포넌트 조건부 렌더링 도중 인증 상태가 변경되어 라우팅을 변경하려고 했기 때문에 발생한 문제입니다.
**[시도한 코드]**
```javascript
useEffect(() => {
if (!currentUser) {
alert('로그인이 필요한 서비스입니다. 홈으로 이동합니다.');
navigate('/');
}
}, [currentUser]);
```
**[발생한 문제]**
`useEffect` 훅 내부에서 `alert`과 `navigate`를 모두 실행하는 방식을 채택했으나 다음과 같은 에러가 발생했습니다.
**[문제 원인]**
에러 메시지를 분석해보면 이전 렌더링에서 호출된 hooks 보다 현재 렌더링에서 hooks가 더 많이 호출된 결과로 발생한 에러임을 알 수 있습니다. 리액트에서 hooks는 매 렌더링마다 동일한 호출을 보장받아야 합니다. 
리액트의 `useEffect`는 렌더링 이후에 실행되므로, 초기 렌더링이 한 번 발생한 후에 `useEffect` 내 로직이 실행됩니다. 즉, …
=> Fix: 마이페이지 조건부 훅 호출 에러 해결
